lowdurability: "Low durability on %item%"
durabilityleft: "%durability% Durability left"
warningsdisabled: "Durability Warnings Disabled!"
warningsenabled: "Durability Warnings Enabled!"
enchantedtrue: "Alerts will only show for enchanted items"
enchantedfalse: "Alerts will show for all items"
invalidarguments: "Invalid Arguments"
armourset: "Armour warning value set to %armour%"
toolset: "Tool warning value set to %tool%"
mustbenumber: "Percent must be a number! ex: 10"
settype: "Warning type has been set to %type%"

displaytime: 10
defaultvalue: 10