lowdurability: "Low durability on"
durabilityleft: "Durability left"
warningsdisabled: "Durability Warnings Disabled!"
warningsenabled: "Durability Warnings Enabled!"
invalidarguments: "Invalid Arguments"
armourset: "Armour warning value set to"
toolset: "Tool warning value set to"
mustbenumber: "Percent must be a number! ex: 10"
settype: "Warning type has been set to"

displaytime: 10